//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MifareOneTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MifareOneTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [0-9A-Fa-f]{32}.
        /// </summary>
        public static string _0_9A_Fa_f_32 {
            get {
                return ResourceManager.GetString("_0_9A_Fa_f_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##Nonce收集完毕##.
        /// </summary>
        public static string _Nonce收集完毕 {
            get {
                return ResourceManager.GetString("_Nonce收集完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +Sector: .
        /// </summary>
        public static string _Sector {
            get {
                return ResourceManager.GetString("_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  个块不同
        ///.
        /// </summary>
        public static string _个块不同 {
            get {
                return ResourceManager.GetString("_个块不同", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##已保存-.
        /// </summary>
        public static string _已保存 {
            get {
                return ResourceManager.GetString("_已保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##已自动保存-.
        /// </summary>
        public static string _已自动保存 {
            get {
                return ResourceManager.GetString("_已自动保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #扇区 .
        /// </summary>
        public static string _扇区 {
            get {
                return ResourceManager.GetString("_扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##文件中的值错误##.
        /// </summary>
        public static string _文件中的值错误 {
            get {
                return ResourceManager.GetString("_文件中的值错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  有数据.
        /// </summary>
        public static string _有数据 {
            get {
                return ResourceManager.GetString("_有数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  有错误.
        /// </summary>
        public static string _有错误 {
            get {
                return ResourceManager.GetString("_有错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##未保存##.
        /// </summary>
        public static string _未保存 {
            get {
                return ResourceManager.GetString("_未保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##程序已被强制停止##.
        /// </summary>
        public static string _程序已被强制停止 {
            get {
                return ResourceManager.GetString("_程序已被强制停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  空扇区.
        /// </summary>
        public static string _空扇区 {
            get {
                return ResourceManager.GetString("_空扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##缓存文件异常##.
        /// </summary>
        public static string _缓存文件异常 {
            get {
                return ResourceManager.GetString("_缓存文件异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ，计算得到BCC=.
        /// </summary>
        public static string _计算得到BCC {
            get {
                return ResourceManager.GetString("_计算得到BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #软件版本 .
        /// </summary>
        public static string _软件版本 {
            get {
                return ResourceManager.GetString("_软件版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##运行出错##.
        /// </summary>
        public static string _运行出错 {
            get {
                return ResourceManager.GetString("_运行出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ##运行完毕##.
        /// </summary>
        public static string _运行完毕 {
            get {
                return ResourceManager.GetString("_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AB文件中一个或两个无效。.
        /// </summary>
        public static string AB文件中一个或两个无效 {
            get {
                return ResourceManager.GetString("AB文件中一个或两个无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACR122U支持已经打开过。.
        /// </summary>
        public static string ACR122U支持已经打开过 {
            get {
                return ResourceManager.GetString("ACR122U支持已经打开过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DUMP文件|*.dump|MFD文件|*.mfd.
        /// </summary>
        public static string DUMP文件_dump_MFD文件_mfd {
            get {
                return ResourceManager.GetString("DUMP文件_dump_MFD文件_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputError.
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KeyA/B/N.
        /// </summary>
        public static string KeyA_B_N {
            get {
                return ResourceManager.GetString("KeyA_B_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCT格式|*.*.
        /// </summary>
        public static string MCT格式 {
            get {
                return ResourceManager.GetString("MCT格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MFD文件|*.mfd;*.dump.
        /// </summary>
        public static string MFD文件_mfd_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MFD文件|*.mfd|DUMP文件|*.dump.
        /// </summary>
        public static string MFD文件_mfd_DUMP文件_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_DUMP文件_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MifareOne Tool.
        /// </summary>
        public static string MifareOne_Tool {
            get {
                return ResourceManager.GetString("MifareOne_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MifareOne Tool - 已取消.
        /// </summary>
        public static string MifareOne_Tool_已取消 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MifareOne Tool - 已终止.
        /// </summary>
        public static string MifareOne_Tool_已终止 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MifareOne Tool - 运行中.
        /// </summary>
        public static string MifareOne_Tool_运行中 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MifareOne Tool - 运行完毕.
        /// </summary>
        public static string MifareOne_Tool_运行完毕 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nfc-bin/collect.exe.
        /// </summary>
        public static string nfc_bin_collect_exe {
            get {
                return ResourceManager.GetString("nfc_bin_collect_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap outline_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("outline_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 。.
        /// </summary>
        public static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_chevron_right_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_chevron_right_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_clear_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_clear_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_done_outline_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_outline_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_sync_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_sync_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_timer_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_timer_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на txt文件|*.txt.
        /// </summary>
        public static string txt文件_txt {
            get {
                return ResourceManager.GetString("txt文件_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UID已改为.
        /// </summary>
        public static string UID已改为 {
            get {
                return ResourceManager.GetString("UID已改为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 不恰当的4字节UID长度.
        /// </summary>
        public static string 不恰当的4字节UID长度 {
            get {
                return ResourceManager.GetString("不恰当的4字节UID长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 使用KeyA（是）或KeyB（否）？.
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否 {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 使用KeyA（是）或KeyB（否），还是不使用（用于全新白卡）（取消）？.
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_ {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 俄语.
        /// </summary>
        public static string 俄语 {
            get {
                return ResourceManager.GetString("俄语", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 共找到 .
        /// </summary>
        public static string 共找到 {
            get {
                return ResourceManager.GetString("共找到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 写入出错.
        /// </summary>
        public static string 写入出错 {
            get {
                return ResourceManager.GetString("写入出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 加载的S50卡文件大小异常。.
        /// </summary>
        public static string 加载的S50卡文件大小异常 {
            get {
                return ResourceManager.GetString("加载的S50卡文件大小异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 加载的文件不存在。.
        /// </summary>
        public static string 加载的文件不存在 {
            get {
                return ResourceManager.GetString("加载的文件不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 危险操作警告.
        /// </summary>
        public static string 危险操作警告 {
            get {
                return ResourceManager.GetString("危险操作警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 同时打开ACR122U支持可能会引起操作速度下降。
        ///请确认是否要继续操作？.
        /// </summary>
        public static string 同时打开ACR122U支持可能会引起操作速度下降_请确认是否 {
            get {
                return ResourceManager.GetString("同时打开ACR122U支持可能会引起操作速度下降_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 字典文件|*.dic.
        /// </summary>
        public static string 字典文件_dic {
            get {
                return ResourceManager.GetString("字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 密钥字典文件|*.dic.
        /// </summary>
        public static string 密钥字典文件_dic {
            get {
                return ResourceManager.GetString("密钥字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 将自动选择首个设备：.
        /// </summary>
        public static string 将自动选择首个设备 {
            get {
                return ResourceManager.GetString("将自动选择首个设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 将要写入的文件存在错误，请用高级模式中的Hex工具打开查看。.
        /// </summary>
        public static string 将要写入的文件存在错误_请用高级模式中的Hex工具打开查看 {
            get {
                return ResourceManager.GetString("将要写入的文件存在错误_请用高级模式中的Hex工具打开查看", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已保存到.
        /// </summary>
        public static string 已保存到 {
            get {
                return ResourceManager.GetString("已保存到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已启用CUID空卡写入补丁.
        /// </summary>
        public static string 已启用CUID空卡写入补丁 {
            get {
                return ResourceManager.GetString("已启用CUID空卡写入补丁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已导出MCT文件.
        /// </summary>
        public static string 已导出MCT文件 {
            get {
                return ResourceManager.GetString("已导出MCT文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已导出密钥字典文件.
        /// </summary>
        public static string 已导出密钥字典文件 {
            get {
                return ResourceManager.GetString("已导出密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已打开。.
        /// </summary>
        public static string 已打开 {
            get {
                return ResourceManager.GetString("已打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已找到！K=.
        /// </summary>
        public static string 已找到_K {
            get {
                return ResourceManager.GetString("已找到_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已指定使用该NFC设备：.
        /// </summary>
        public static string 已指定使用该NFC设备 {
            get {
                return ResourceManager.GetString("已指定使用该NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已更新扇区.
        /// </summary>
        public static string 已更新扇区 {
            get {
                return ResourceManager.GetString("已更新扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 已重置并新建卡。.
        /// </summary>
        public static string 已重置并新建卡 {
            get {
                return ResourceManager.GetString("已重置并新建卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行CUID/FUID卡片写入…….
        /// </summary>
        public static string 开始执行CUID_FUID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行CUID_FUID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行HardNested收集数据…….
        /// </summary>
        public static string 开始执行HardNested收集数据 {
            get {
                return ResourceManager.GetString("开始执行HardNested收集数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行HardNested解密强化卡…….
        /// </summary>
        public static string 开始执行HardNested解密强化卡 {
            get {
                return ResourceManager.GetString("开始执行HardNested解密强化卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行MFOC解密…….
        /// </summary>
        public static string 开始执行MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行UFUID卡片锁定…….
        /// </summary>
        public static string 开始执行UFUID卡片锁定 {
            get {
                return ResourceManager.GetString("开始执行UFUID卡片锁定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行UID卡片全格…….
        /// </summary>
        public static string 开始执行UID卡片全格 {
            get {
                return ResourceManager.GetString("开始执行UID卡片全格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行UID卡片写入…….
        /// </summary>
        public static string 开始执行UID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行UID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行UID卡片设定卡号…….
        /// </summary>
        public static string 开始执行UID卡片设定卡号 {
            get {
                return ResourceManager.GetString("开始执行UID卡片设定卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行UID卡片读取…….
        /// </summary>
        public static string 开始执行UID卡片读取 {
            get {
                return ResourceManager.GetString("开始执行UID卡片读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行全加密卡片爆破…….
        /// </summary>
        public static string 开始执行全加密卡片爆破 {
            get {
                return ResourceManager.GetString("开始执行全加密卡片爆破", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行写入M1卡片…….
        /// </summary>
        public static string 开始执行写入M1卡片 {
            get {
                return ResourceManager.GetString("开始执行写入M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行字典模式MFOC解密…….
        /// </summary>
        public static string 开始执行字典模式MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行字典模式MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行扫描卡片…….
        /// </summary>
        public static string 开始执行扫描卡片 {
            get {
                return ResourceManager.GetString("开始执行扫描卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行格式化M1卡片…….
        /// </summary>
        public static string 开始执行格式化M1卡片 {
            get {
                return ResourceManager.GetString("开始执行格式化M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行检测卡片加密…….
        /// </summary>
        public static string 开始执行检测卡片加密 {
            get {
                return ResourceManager.GetString("开始执行检测卡片加密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行检测设备…….
        /// </summary>
        public static string 开始执行检测设备 {
            get {
                return ResourceManager.GetString("开始执行检测设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行读取卡片…….
        /// </summary>
        public static string 开始执行读取卡片 {
            get {
                return ResourceManager.GetString("开始执行读取卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 开始执行重置UID卡片卡号…….
        /// </summary>
        public static string 开始执行重置UID卡片卡号 {
            get {
                return ResourceManager.GetString("开始执行重置UID卡片卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 当前扇区数据仍有错误，不能执行修改。.
        /// </summary>
        public static string 当前扇区数据仍有错误_不能执行修改 {
            get {
                return ResourceManager.GetString("当前扇区数据仍有错误_不能执行修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 当前选定扇区：？？.
        /// </summary>
        public static string 当前选定扇区 {
            get {
                return ResourceManager.GetString("当前选定扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 当前选定扇区：.
        /// </summary>
        public static string 当前选定扇区0 {
            get {
                return ResourceManager.GetString("当前选定扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 您可以上传到云计算服务节点进行计算。.
        /// </summary>
        public static string 您可以上传到云计算服务节点进行计算 {
            get {
                return ResourceManager.GetString("您可以上传到云计算服务节点进行计算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 您已经运行了MifareOne Tool，打开多个本程序可能会造成冲突及不可预料到的错误。
        ///确认要继续吗？.
        /// </summary>
        public static string 您已经运行了MifareOne_Tool_打开多个本程序可能 {
            get {
                return ResourceManager.GetString("您已经运行了MifareOne_Tool_打开多个本程序可能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 您正在试图重复运行.
        /// </summary>
        public static string 您正在试图重复运行 {
            get {
                return ResourceManager.GetString("您正在试图重复运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的密钥源。
        ///操作终止。.
        /// </summary>
        public static string 您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的 {
            get {
                return ResourceManager.GetString("您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 扇区.
        /// </summary>
        public static string 扇区 {
            get {
                return ResourceManager.GetString("扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 扇区 .
        /// </summary>
        public static string 扇区0 {
            get {
                return ResourceManager.GetString("扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 打开了.
        /// </summary>
        public static string 打开了 {
            get {
                return ResourceManager.GetString("打开了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 打开出错.
        /// </summary>
        public static string 打开出错 {
            get {
                return ResourceManager.GetString("打开出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 提示信息.
        /// </summary>
        public static string 提示信息 {
            get {
                return ResourceManager.GetString("提示信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 文件内不是含有64个块数据，可能不完整或不兼容。.
        /// </summary>
        public static string 文件内不是含有64个块数据_可能不完整或不兼容 {
            get {
                return ResourceManager.GetString("文件内不是含有64个块数据_可能不完整或不兼容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 无密钥.
        /// </summary>
        public static string 无密钥 {
            get {
                return ResourceManager.GetString("无密钥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 无法找到MFF08程序文件。
        ///操作终止。.
        /// </summary>
        public static string 无法找到MFF08程序文件_操作终止 {
            get {
                return ResourceManager.GetString("无法找到MFF08程序文件_操作终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 显示扇区.
        /// </summary>
        public static string 显示扇区 {
            get {
                return ResourceManager.GetString("显示扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 有任务运行中，不可执行。.
        /// </summary>
        public static string 有任务运行中_不可执行 {
            get {
                return ResourceManager.GetString("有任务运行中_不可执行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 未知.
        /// </summary>
        public static string 未知 {
            get {
                return ResourceManager.GetString("未知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 未选择有效key.mfd。.
        /// </summary>
        public static string 未选择有效key_mfd {
            get {
                return ResourceManager.GetString("未选择有效key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 本地版本 .
        /// </summary>
        public static string 本地版本 {
            get {
                return ResourceManager.GetString("本地版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 标准.
        /// </summary>
        public static string 标准 {
            get {
                return ResourceManager.GetString("标准", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 正在使用智能KeyABN….
        /// </summary>
        public static string 正在使用智能KeyABN {
            get {
                return ResourceManager.GetString("正在使用智能KeyABN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 正在打开ACR122U支持…….
        /// </summary>
        public static string 正在打开ACR122U支持 {
            get {
                return ResourceManager.GetString("正在打开ACR122U支持", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 正在检索是否存在key.mfd….
        /// </summary>
        public static string 正在检索是否存在key_mfd {
            get {
                return ResourceManager.GetString("正在检索是否存在key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 没有发现任何有效的NFC设备。.
        /// </summary>
        public static string 没有发现任何有效的NFC设备 {
            get {
                return ResourceManager.GetString("没有发现任何有效的NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 秒.
        /// </summary>
        public static string 秒 {
            get {
                return ResourceManager.GetString("秒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 空闲.
        /// </summary>
        public static string 空闲 {
            get {
                return ResourceManager.GetString("空闲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 终端内容已保存至m1t.log文件.
        /// </summary>
        public static string 终端内容已保存至m1t_log文件 {
            get {
                return ResourceManager.GetString("终端内容已保存至m1t_log文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 设备串口：.
        /// </summary>
        public static string 设备串口 {
            get {
                return ResourceManager.GetString("设备串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 设备忙.
        /// </summary>
        public static string 设备忙 {
            get {
                return ResourceManager.GetString("设备忙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 设置错误，请修改。.
        /// </summary>
        public static string 设置错误_请修改 {
            get {
                return ResourceManager.GetString("设置错误_请修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 识别了以下设备：.
        /// </summary>
        public static string 识别了以下设备 {
            get {
                return ResourceManager.GetString("识别了以下设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区UID校验值错误，已经自动为您更正。
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_已经自动为您更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已经自动为您更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区UID校验值错误，已自动更正。
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_已自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区UID校验值错误，请点击打开扇区0来自动更正。
        ///.
        /// </summary>
        public static string 该扇区UID校验值错误_请点击打开扇区0来自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_请点击打开扇区0来自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区一切正常。
        ///.
        /// </summary>
        public static string 该扇区一切正常 {
            get {
                return ResourceManager.GetString("该扇区一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区访问控制位损坏，写入将会损坏卡片，已重新设置。
        ///.
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区访问控制位损坏，写入将会损坏卡片，请重新设置。
        ///.
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区访问控制位无效，写入将会损坏卡片，已重新设置。
        ///.
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该扇区访问控制位无效，写入将会损坏卡片，请重新设置。
        ///.
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该操作将会清空UID卡内全部数据！！！
        ///清空后不可恢复！请确认是否要继续操作？.
        /// </summary>
        public static string 该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否 {
            get {
                return ResourceManager.GetString("该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该操作将会锁死UFUID卡片！！！
        ///锁死后不可恢复！无法再次更改0块！请确认是否要继续操作？.
        /// </summary>
        public static string 该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0 {
            get {
                return ResourceManager.GetString("该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该文件一切正常。.
        /// </summary>
        public static string 该文件一切正常 {
            get {
                return ResourceManager.GetString("该文件一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 该文件存在以下错误：
        ///.
        /// </summary>
        public static string 该文件存在以下错误 {
            get {
                return ResourceManager.GetString("该文件存在以下错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请检查接线是否正确/驱动是否正常安装/设备电源是否已经打开（对于具有电源开关的型号）。.
        /// </summary>
        public static string 请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_ {
            get {
                return ResourceManager.GetString("请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请输入UID号.
        /// </summary>
        public static string 请输入UID号 {
            get {
                return ResourceManager.GetString("请输入UID号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请输入已知Key.
        /// </summary>
        public static string 请输入已知Key {
            get {
                return ResourceManager.GetString("请输入已知Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请输入已知的Key，以英文半角逗号分隔。.
        /// </summary>
        public static string 请输入已知的Key_以英文半角逗号分隔 {
            get {
                return ResourceManager.GetString("请输入已知的Key_以英文半角逗号分隔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请输入需要写入的UID卡号，共8位十六进制数，如E44A3BF1。.
        /// </summary>
        public static string 请输入需要写入的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要写入的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请输入需要更改的UID卡号，共8位十六进制数，如E44A3BF1。.
        /// </summary>
        public static string 请输入需要更改的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要更改的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择MCT.txt文件保存位置及文件名.
        /// </summary>
        public static string 请选择MCT_txt文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MCT_txt文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择MFD文件保存位置及文件名.
        /// </summary>
        public static string 请选择MFD文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MFD文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择一个包含目标卡密钥的MFD文件（通常是已经破解出的该卡的MFD文件）.
        /// </summary>
        public static string 请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡 {
            get {
                return ResourceManager.GetString("请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择密钥字典文件保存位置及文件名.
        /// </summary>
        public static string 请选择密钥字典文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择密钥字典文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择最后一次写卡导致0块损坏的卡数据文件.
        /// </summary>
        public static string 请选择最后一次写卡导致0块损坏的卡数据文件 {
            get {
                return ResourceManager.GetString("请选择最后一次写卡导致0块损坏的卡数据文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要写入的MFD文件.
        /// </summary>
        public static string 请选择需要写入的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要写入的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要打开的MCT格式文件.
        /// </summary>
        public static string 请选择需要打开的MCT格式文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MCT格式文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要打开的MFD文件.
        /// </summary>
        public static string 请选择需要打开的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要打开的MFD文件(比较A).
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较A {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要打开的MFD文件(比较B).
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较B {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 请选择需要打开的密钥字典文件.
        /// </summary>
        public static string 请选择需要打开的密钥字典文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 输入的UID号不合法.
        /// </summary>
        public static string 输入的UID号不合法 {
            get {
                return ResourceManager.GetString("输入的UID号不合法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 运行中.
        /// </summary>
        public static string 运行中 {
            get {
                return ResourceManager.GetString("运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 运行时间:.
        /// </summary>
        public static string 运行时间 {
            get {
                return ResourceManager.GetString("运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 选择key.mfd.
        /// </summary>
        public static string 选择key_mfd {
            get {
                return ResourceManager.GetString("选择key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 错误.
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
    }
}
